name: Docker Build

on: push

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Docker Build
      uses: tpology/actions/docker-build@v1
      with:
        image-names: smxlong/tpology-auth
        docker-username: ${{ secrets.DOCKER_USERNAME }}
        docker-password: ${{ secrets.DOCKER_PASSWORD }}
